[package]
name = "minimal"
version = "0.1.0"

[dependencies]
log = "0.4"
web_logger = "0.1"
stdweb = "^0.4.14"
yew = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
# chrono = { version = "0.4.7", features = ["serde"] }
chrono = "0.4.7"
